# Generated by Django 4.1.7 on 2023-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
